---
title: "Strings"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
```

```{r}
#criando uma string básica
'Isso é uma string'
"Isso também é uma string"

x <- 'variável :)'
print(x)

y <- '\u00b5' #unicode
print(y)
'\n' #insrese uma nova linha 
'\t' #um tab


c('one','two', 'three') #um vetor de strings
```
```{r}
str_length(c('a','R for data science', NA)) #retorna a quantidade de caracteres
```

```{r}
#combinação de strings

str_c('x','y') #combina x e y
str_c('x','y', sep = ',') #combina e insere um caractere separador
x <- c('abc', NA)
str_c('|', x, '|') #combinação de strings em variaveis
str_c('|', str_replace_na(x), '|') #printa o valor NA com a formatação
str_c('prefix-', c('a','b','c'), '-suffix') #atribui cada string aos elementos do vetor de strings

name <- 'Hadley'
time_of_day <- 'morning'
birthday <- FALSE

str_c('Good', time_of_day, '', name, 
      if(birthday) 'and HAPPY BIRTHDAY')

str_c(c('x', 'y', 'z'), collapse = ',') #colapsa o vetor de string em uma string

```
```{r}
#subconjuntos de strings
x <- c('Apple','Banana', 'Pear')
str_sub(x, 1, 3) #extraimos todos elementos pegando do primeiro ao terceiro índice
str_sub(x, -1, -3) #extrai de trás para frente

x <- c('Apple','Banana', 'Pear')
str_to_lower(str_sub(x,1,str_length(x))) #passamos a extração em minusculas
```
```{r}
#localizações em strings
str_to_upper(c('i','i'))
str_to_upper(c('i','i'), locale = 'tr') #observe a diferença da impressão

x <- c('apple','eggplant','banana')

str_sort(x, locale = 'en')
str_sort(x, locale = 'haw') #observe como em hawaiano é diferente a ordenação
```
## Combinando padrões e expressões regulares

```{r}
#visualizando partes
x <- c('apple','banana','pear')
str_view(x, 'an') #veremos as strings em x que contém 'an'

```
```{r}
#operador .
str_view(x, '.a.') #veremos onde "a" está cercado por outros caracteres

#verificando em torno de "."

dot <- '\\.' #criando uma expressão para "\."
writeLines(dot) #vendo a expressão, ela possui somente um "\"

str_view(c('abc','a.c','bef'), 'a\\.c')

x <- 'a\\b'
writeLines(x) #vendo a expressão de fato

str_view(x,'\\\\') #vendo onde há '\' na expressão
```
```{r}
## âncoras
x <- c('apple','banana','pear')
str_view(x, '^a') #vemos onde há "a" no começo
str_view(x, 'a$') #vemos onde há "a" no final

x <- c('apple pie','apple', 'apple cake') 
str_view(x, '^apple$') #vemos onde começa termina com 'apple'
```
```{r}
## classes de caracteres e alternativas
str_view(c('grey','gray'), 'gr(e|a)y') #palavras desta estrutura com e ou a
```

```{r}
## repetição
x <- '1888 é o maior número em números romanos: MDCCCLXXXVIII'

str_view(x, 'CC?')
str_view(x, 'CC+')
str_view(x, 'C[LX]+')
str_view(x, 'C{2}')
str_view(x, 'C{2,}')
str_view(x, 'C{2,3}')
```
```{r}
## agrupamento
str_view(fruit, '(..)\\1', match = TRUE) #verifica onde há grupo de letras repetidos
```

